[book]
authors = ["TheVeryDarkness"]
language = "en"
src = "src"
title = "dev"

[build]
extra-watch-dirs = ["../../src", "../../src/Cargo.lock"]

# [preprocessor.katex]
# after = ["links"]

[preprocessor.numbering]
# after = ["katex"]
command = "cargo run --bin mdbook-numbering"

[preprocessor.numbering.heading]
numbering-style = "consecutive"

[output.html]

[output.markdown]
