[book]
authors = ["TheVeryDarkness"]
language = "en"
multilingual = false
src = "src"
title = "dev"

[build]
extra-watch-dirs = ["../../src"]

[preprocessor.numbering]
command = "cargo run --bin mdbook-numbering"

[preprocessor.numbering.heading]
numbering-style = "consecutive"

[output.html]

[output.markdown]
