[book]
authors = ["TheVeryDarkness"]
language = "en"
src = "src"
title = "dev"

[build]
extra-watch-dirs = ["../../src", "../../src/Cargo.lock"]

[preprocessor.katex]

[preprocessor.numbering]
command = "cargo run --bin mdbook-numbering"

[preprocessor.numbering.heading]
numbering-style = "consecutive"

[output.html]
git-repository-url = "https://github.com/TheVeryDarkness/mdbook-numbering/"
edit-url-template = "https://github.com/TheVeryDarkness/mdbook-numbering/edit/master/examples/dev/{path}"
mathjax-support = true

[output.html.print]
enable = true
page-break = false

[output.markdown]

[output.pdf]
optional = true
print-background = true
generate-document-outline = true
generate-tagged-pdf = true
